version: '3.8'  

services:  
  db:  
    image: postgres:13  
    container_name: postgres_dev  
    environment:  
      POSTGRES_DB: news  
      POSTGRES_USER: newsuser  
      POSTGRES_PASSWORD: newspass  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
    ports:  
      - "5432:5432"  

  db_explorer:  
    image: dpage/pgadmin4  
    container_name: pgadmin  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:  
      - "8081:80"  
    volumes:  
      - pgadmin_data:/var/lib/pgadmin  
    depends_on:  
      - db  

volumes:  
  postgres_data:  
  pgadmin_data:  
